### ISSUE TITLE
Image for 5.2

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.docker#112] opened 2019-04-06 07:23 UTC
Having a 5.2 image would be great for testing/demos. Is there any blocker preventing it?

**Comment by avoinea** [comment] 2019-04-17 21:04
I did a commit for this https://github.com/plone/plone.docker/commit/1cbef827aa6ab80bc1b9ce2f7409bb5071338355

Unfortunately, I don't have the admin rights on this repo anymore (@svx ?!?) thus I can't add the auto-builds on [docker-hub](https://cloud.docker.com/u/plone/repository/docker/plone/plone/builds)

**Comment by svx** [comment] 2019-04-18 03:49
@avoinea I did not changed anything on Dockerhub.
I will see if I can figure out what is going on there. :)

**Comment by avoinea** [comment] 2019-04-18 07:43
@svx I did remove the DockerHub link with GitHub while trying to add new tags. Then, when I tried to restore it, I found that I don't have the right permissions on this github repo anymore :(

**Comment by svx** [comment] 2019-04-18 07:53
@avoinea I just checked, we have all the same permissions, your account, too :)

Maybe it has something to do with: https://success.docker.com/article/i-have-issues-triggering-autobuilds ?

**Comment by avoinea** [comment] 2019-04-18 08:01
@svx 

```
To fix this issue, make sure that your linked Github or Bitbucket account has 
admin permissions for the repository you are trying to configure autobuilds for.
```

Thus, as I don't have `admin` rights on this GitHub repo, I can't select it:

![2019-04-18-105659_1026x631_scrot](https://user-images.githubusercontent.com/323385/56345582-bf290200-61c8-11e9-87a3-3146f8d29038.png)

**Comment by svx** [comment] 2019-04-18 08:22
I "synced" the docker -> GitHub settings/hooks

![plone-docker-auto](https://user-images.githubusercontent.com/358860/56346978-93efe400-61c3-11e9-8e10-444fdf0e4c3a.png)

As far as I can see there is no tag for 5.2 showing up, yet.

**Comment by avoinea** [comment] 2019-04-18 09:31
> I "synced" the docker -> GitHub settings/hooks

I think that's an old an deprecated image and we should remove it from docker hub (don't know who added it there in the first place) to avoid this kind of confusion :)

The one I'm talking is: https://cloud.docker.com/u/plone/repository/docker/plone/plone. Either this one is not the official one, as we have https://hub.docker.com/_/plone. 

But we use it as a pre-release. Or in this case, release-candidates.

> As far as I can see there is no tag for 5.2 showing up, yet.

As the releases are in folders and not as Git tags, we add tags manually on DockerHub once the new folders pop-in.

**Comment by svx** [comment] 2019-04-18 14:08
![plone docker-auto](https://user-images.githubusercontent.com/358860/56366798-3758ed00-61f4-11e9-8e1f-12fef05699c1.png)

**Comment by avoinea** [comment] 2019-04-18 16:22
@svx Thank you!

Building... `:5.2rc1` and `:5.2rc1-alpine`
![2019-04-18-192135_1139x225_scrot](https://user-images.githubusercontent.com/323385/56375843-397c7500-620f-11e9-9ebb-2f2dfda892da.png)

**Comment by avoinea** [comment] 2019-04-24 20:29
`:5.2rc1-python2` also on it's way!

**Comment by avoinea** [comment] 2019-07-23 08:18
Duplicate of #119

**Closed by avoinea** 2019-07-23 08:18 UTC
Labels: new release
