### ISSUE TITLE
SSL: Plone behind Nginx Ingress

### ISSUE THREAD

**Issue by georgesouzafarias** [plone/plone.docker#140] opened 2020-09-18 20:14 UTC
Hello everyone,

I'm configuring a plone instance using a docker image(plone:5.2.1) on Kubernetes.

Everything run very well, but when I force the TSL redirect the page brokes.

![image](https://user-images.githubusercontent.com/4741919/93640369-dc22bf80-f9d0-11ea-9330-8f45477a12e1.png)

Seeing the page source, we can see that URL is set as **http://<URL>.**

If I disable the redirect the page works fine.

So, my question: Has anyone been using the Plone behind a nginx ingress on k8s?

Thank you.

**Comment by avoinea** [comment] 2020-09-21 08:18
@georgesouzafarias I think the issue is only with this Zope Welcome screen. The issue should be fixed if you point your nginx directly to the Plone instance like:

```
 location / {
     proxy_pass http://myzope/VirtualHostBase/https/www.mysite.com:443/Plone/VirtualHostRoot/;
 }
```

See more about it https://docs.plone.org/manage/deploying/front-end/nginx.html#minimal-nginx-front-end-configuration-for-plone-on-ubuntu-debian-linux and https://www.starzel.de/blog/securing-plone-sites-with-https-and-nginx

**Closed by avoinea** 2020-09-21 08:18 UTC
